// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/role/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/role/repository.go -destination=internal/mocks/mock_role_repository.go -package=mocks -mock_names=Repository=MockRoleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	role "github.com/yuki5155/go-google-auth/internal/domain/role"
	user "github.com/yuki5155/go-google-auth/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of Repository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// CreateRoleRequest mocks base method.
func (m *MockRoleRepository) CreateRoleRequest(ctx context.Context, request *role.RoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoleRequest", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoleRequest indicates an expected call of CreateRoleRequest.
func (mr *MockRoleRepositoryMockRecorder) CreateRoleRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoleRequest", reflect.TypeOf((*MockRoleRepository)(nil).CreateRoleRequest), ctx, request)
}

// GetPendingRequestByUserID mocks base method.
func (m *MockRoleRepository) GetPendingRequestByUserID(ctx context.Context, userID string) (*role.RoleRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingRequestByUserID", ctx, userID)
	ret0, _ := ret[0].(*role.RoleRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingRequestByUserID indicates an expected call of GetPendingRequestByUserID.
func (mr *MockRoleRepositoryMockRecorder) GetPendingRequestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingRequestByUserID", reflect.TypeOf((*MockRoleRepository)(nil).GetPendingRequestByUserID), ctx, userID)
}

// GetRoleRequest mocks base method.
func (m *MockRoleRepository) GetRoleRequest(ctx context.Context, requestID string) (*role.RoleRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleRequest", ctx, requestID)
	ret0, _ := ret[0].(*role.RoleRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleRequest indicates an expected call of GetRoleRequest.
func (mr *MockRoleRepositoryMockRecorder) GetRoleRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleRequest", reflect.TypeOf((*MockRoleRepository)(nil).GetRoleRequest), ctx, requestID)
}

// GetUserRole mocks base method.
func (m *MockRoleRepository) GetUserRole(ctx context.Context, userID string) (*role.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID)
	ret0, _ := ret[0].(*role.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockRoleRepositoryMockRecorder) GetUserRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockRoleRepository)(nil).GetUserRole), ctx, userID)
}

// GetUserRoleByEmail mocks base method.
func (m *MockRoleRepository) GetUserRoleByEmail(ctx context.Context, email string) (*role.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoleByEmail", ctx, email)
	ret0, _ := ret[0].(*role.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoleByEmail indicates an expected call of GetUserRoleByEmail.
func (mr *MockRoleRepositoryMockRecorder) GetUserRoleByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoleByEmail", reflect.TypeOf((*MockRoleRepository)(nil).GetUserRoleByEmail), ctx, email)
}

// ListRoleRequestsByStatus mocks base method.
func (m *MockRoleRepository) ListRoleRequestsByStatus(ctx context.Context, status role.RequestStatus) ([]*role.RoleRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleRequestsByStatus", ctx, status)
	ret0, _ := ret[0].([]*role.RoleRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleRequestsByStatus indicates an expected call of ListRoleRequestsByStatus.
func (mr *MockRoleRepositoryMockRecorder) ListRoleRequestsByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleRequestsByStatus", reflect.TypeOf((*MockRoleRepository)(nil).ListRoleRequestsByStatus), ctx, status)
}

// ListRoleRequestsByUserID mocks base method.
func (m *MockRoleRepository) ListRoleRequestsByUserID(ctx context.Context, userID string) ([]*role.RoleRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleRequestsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*role.RoleRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleRequestsByUserID indicates an expected call of ListRoleRequestsByUserID.
func (mr *MockRoleRepositoryMockRecorder) ListRoleRequestsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleRequestsByUserID", reflect.TypeOf((*MockRoleRepository)(nil).ListRoleRequestsByUserID), ctx, userID)
}

// ListUsersByRole mocks base method.
func (m *MockRoleRepository) ListUsersByRole(ctx context.Context, arg1 user.Role) ([]*role.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersByRole", ctx, arg1)
	ret0, _ := ret[0].([]*role.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersByRole indicates an expected call of ListUsersByRole.
func (mr *MockRoleRepositoryMockRecorder) ListUsersByRole(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersByRole", reflect.TypeOf((*MockRoleRepository)(nil).ListUsersByRole), ctx, arg1)
}

// UpdateRoleRequest mocks base method.
func (m *MockRoleRepository) UpdateRoleRequest(ctx context.Context, request *role.RoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoleRequest", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoleRequest indicates an expected call of UpdateRoleRequest.
func (mr *MockRoleRepositoryMockRecorder) UpdateRoleRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoleRequest", reflect.TypeOf((*MockRoleRepository)(nil).UpdateRoleRequest), ctx, request)
}

// UpsertUserRole mocks base method.
func (m *MockRoleRepository) UpsertUserRole(ctx context.Context, userRole *role.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserRole", ctx, userRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserRole indicates an expected call of UpsertUserRole.
func (mr *MockRoleRepositoryMockRecorder) UpsertUserRole(ctx, userRole any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserRole", reflect.TypeOf((*MockRoleRepository)(nil).UpsertUserRole), ctx, userRole)
}
